version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: workflowx-postgres
    environment:
      POSTGRES_DB: workflowx
      POSTGRES_USER: workflowx_user
      POSTGRES_PASSWORD: workflowx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - workflowx-network

  redis:
    image: redis:7-alpine
    container_name: workflowx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workflowx-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: workflowx-backend
    environment:
      DATABASE_URL: postgresql://workflowx_user:workflowx_password@postgres:5432/workflowx
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - workflowx-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: workflowx-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - workflowx-network

volumes:
  postgres_data:
  redis_data:

networks:
  workflowx-network:
    driver: bridge